import Head from 'next/head'
import { Layout } from '../components/Layout'
import MainSection from '../components/mainSection'
import { SectionPresentation } from '../components/sectionLetterPresent'
import { SectionPorfolio } from '../components/sectionPortfolio';


export default function Home() {


  return (
    <div>
      <Head>
        <title>Site of Alejandro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <MainSection />
        <SectionPresentation />
        <SectionPorfolio />
      </Layout>
    </div>
  )
}
