import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube } from 'react-icons/ai'
import Image from 'next/image'
import avatar from '../public/avataaars.svg'
import designer from '../public/designer.jpg'
import web1 from '../public/web1.jpg'
// import web2 from '../public/web2.jpg' 
import web3 from '../public/web3.jpg'
// import './../styles/personalited.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Site of Alejandro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:text-center md:px-20 lg:px-40'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl'>Alejandro</h1>
            <ul className='flex items-center'>
              <li> Home </li>
              <li> About </li>
              <li> Contact </li>
              <li><a href='#' className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'>Resumen</a></li>
              <li><BsFillMoonStarsFill className='cursor-pointer text-2xl' /></li>

            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-3xl py-2 text-teal-500 font-medium md:text-6xl xl:text-8xl' >Alejandro Obregon</h2>

            <p className='text-md py-5 leading-8 text-gray-800'>Full Stack Developer</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillLinkedin />
            <AiFillTwitterCircle />
            <AiFillYoutube />
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={avatar} alt="Picture of the author" fill style={{ objectFit: 'cover' }} />
          </div>
        </section>
        <section className='text-center'>
          <h3 className='text-3xl py-1'>Service I offer</h3>
          <p className='text-md py-2 leading-8 text-gray-800 text-justify md:text-xl max-w-3xl mx-auto'>
            Since the beginning of my career, I have been working on a wide range of <span className='text-cyan-500'>technologies</span> and <span className='text-cyan-500'>projects.</span> I have worked with different teams and have been able to develop my skills in different areas. I have worked with different teams and have been able to develop my skills in different areas.
          </p>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg flex flex-col items-center p-10 rounded-2xl' >
              <Image src={designer} alt="Picture of the author" style={{ objectFit: 'cover', borderRadius: '50px', width: '80px', height: '80px' }} />
              <h3 className='text-xl font-medium pt-8 pb-2'>Beautifull Designes</h3>
              <p className='text-md py-2 leading-8 text-gray-800 text-justify'>
                Creating elegant designs soited for your business. I will create a design that will make your business stand out. I will create a design that will make your business stand out. I will create a design that will make your business stand out.
              </p>
            </div>
            <div className='text-center shadow-lg flex flex-col items-center p-10 rounded-2xl' >
              <Image src={designer} alt="Picture of the author" style={{ objectFit: 'cover', borderRadius: '50px', width: '80px', height: '80px' }} />
              <h3 className='text-xl font-medium pt-8 pb-2'>Beautifull Designes</h3>
              <p className='text-md py-2 leading-8 text-gray-800 text-justify'>
                Creating elegant designs soited for your business. I will create a design that will make your business stand out. I will create a design that will make your business stand out. I will create a design that will make your business stand out.
              </p>
            </div>
            <div className='text-center shadow-lg flex flex-col items-center p-10 rounded-2xl' >
              <Image src={designer} alt="Picture of the author" style={{ objectFit: 'cover', borderRadius: '50px', width: '80px', height: '80px' }} />
              <h3 className='text-xl font-medium pt-8 pb-2'>Beautifull Designes</h3>
              <p className='text-md py-2 leading-8 text-gray-800 text-justify'>
                Creating elegant designs soited for your business. I will create a design that will make your business stand out. I will create a design that will make your business stand out. I will create a design that will make your business stand out.
              </p>
            </div>


          </div>
        </section>
        <section>
          <div className='py-10'>
            <h3 className='text-3xl py-1'>Portofolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800 text-justify max-w-3xl m-auto'>
              Since the beginning of my career, I have been working on a wide range of <span className='text-cyan-500'>technologies</span> and <span className='text-cyan-500'>projects.</span> I have worked with different teams and have been able to develop my skills in different areas. I have worked with different teams and have been able to develop my skills in different areas.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='relative w-100 h-100'>
              <Image src={web1} alt="Picture of the author" style={{ objectFit: 'cover', borderRadius: '5px' }} className='img-portofolio' />
            </div>
            <div>
              <Image src={web3} alt="Picture of the author" style={{ objectFit: 'cover', borderRadius: '5px' }} className='img-portofolio' />
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
